<?php

return [
    'title' => 'Marie-Chrystelle Cheikha',
    'paragraph1' => 'La mode, c\'est une histoire de famille. Le nom CHEIKHA est associé au domaine de la mode depuis près de 30 ans. Marie-Chrystelle Cheikha, la fondatrice de Runway 2 Doorway, ne peut donc pas renier ses origines, pour notre plus grand bonheur&nbsp;! Pleins feux sur celle qui nous fait le plaisir d\'avoir créé une plateforme en ligne de services de stylisme personnalisé.',
    'paragraph2' => 'Marie-Chrystelle Cheikha baigne dans l\'univers de la mode depuis son très jeune âge. En effet, cette dernière a grandi au même rythme que les boutiques de vêtements haut de gamme pour femme de ses parents, qui ont ouvert leur tout premier magasin en 1988. Après 30 ans à se tailler une place importante dans le prêt-à-porter féminin, l\'entreprise de ses parents compte aujourd\'hui quatre boutiques, une trentaine d\'employés et offre près de 40 marques exclusives.',
    'paragraph3' => 'La pomme ne tombe jamais loin de l\'arbre dit-on, et c\'est bien vrai pour Marie-Chrystelle qui a décidé de perpétuer l\'expertise familiale dans l\'art d\'habiller les femmes au quotidien.',
    'paragraph4' => 'Elle s\'est donc lancée dans des études du vaste monde de la mode. D\'abord en commercialisation de la mode au Campus Notre-Dame-de-Foy de Québec, puis dans le programme anglophone offert au Collège LaSalle de Montréal.',
    'paragraph5' => 'Désirant parfaire ses connaissances, elle part à l\'étranger à la découverte de nouvelles cultures et de tendances dans l\'optique d\'en faire profiter l\'entreprise familiale en pleine expansion. C\'est donc en 2011, riche de plusieurs formations et expériences, qu\'elle intègre officiellement les rangs du Groupe Cheikha. Son flair inné pour les belles choses l\'amène à exercer des rôles importants au sein de l\'entreprise, soit celui d\'acheteuse, de styliste et de gérante de boutique. Ses conseils vestimentaires judicieux font qu\'elle est immédiatement appréciée des clientes du Groupe Cheikha.',
    'paragraph6' => '« La femme avant tout » est la devise à laquelle Marie-Chrystelle adhère totalement. Ce pourquoi elle a voulu en offrir davantage aux femmes d\'aujourd\'hui, qui ont une réalité bien différente d\'il y a 30 ans. Femme de carrière, maman à la maison, voyageant partout dans le monde, beaucoup de femmes ont peine à trouver du temps pour magasiner et surtout, de bien le faire.',
    'paragraph7' => 'Avec le service de stylisme Runway 2 Doorway, Marie-Chrystelle veut permettre aux femmes occupées de dénicher des vêtements griffés de la saison livrés directement à la maison, en plus de profiter de conseils vestimentaires judicieux personnalisés à celle qui est derrière l\'écran. Et le plus beau dans tout cela est que CE SERVICE EST TOUT À FAIT « GRATUIT ». De plus, Marie-Chrystelle se donne pour mission de démocratiser l\'accès à ces vêtements haut de gamme en promettant à ses clientes des ventes exclusives.',
    'paragraph8' => 'Une expérience de magasinage unique signée Marie-Chrystelle Cheikha.',
];